spring:
  application:
    name: batch-system

  # SQLite
  datasource:
    url: jdbc:sqlite:batch.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        "[format_sql]": true

  # Spring Batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
