spring:
  application:
    name: batch-system

  # SQLite
  datasource:
    url: jdbc:sqlite:batch.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true # 실행되는 SQL을 콘솔에 보여줌 (강의 시 유용)

    hibernate:
      ddl-auto: update # Entity를 보고 테이블을 자동 생성/수정함

    properties:
      hibernate:
        "[format_sql]": true # SQL을 보기 좋게 줄바꿈 해줌

  # Spring Batch
  batch:
    jdbc:
      initialize-schema: always # 배치가 실행될 때 필요한 메타 테이블들을 자동 생성해줌
    job:
      enabled: false
